name: all_about_whats_new
description: A Project created by allaboutapps.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0

  go_router: ^14.2.7
  sheet: ^1.0.0
  easy_localization: ^3.0.3
  json_serializable: ^6.7.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.2
  flutter_animate: ^4.5.0
  clock: ^1.1.1
  flutter_markdown: ^0.7.4+1
  url_launcher: ^6.2.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: any
  go_router_builder: ^2.3.4
